use_frameworks!

target 'HRSafeComponent_Example' do
  pod 'HRSafeComponent', :path => '../'

  target 'HRSafeComponent_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
